/* eslint-disable @typescript-eslint/no-explicit-any */
export interface ICountry {
  name: string;
  code: string;
  country_code: string;
  dial_code: string;
  flag: string;
  currency: string;
  currency_name: string;
  currency_symbol: string;
}

export const getCountryByCode = (country_code: string) => {
  return COUNTRY.find(
    (c) => c.country_code.toLowerCase() === country_code.toLowerCase()
  );
};

export const defaultCountry: ICountry = {
  name: "United Arab Emirates",
  code: "AE",
  country_code: "UAE",
  dial_code: "+971",
  flag: "https://flagcdn.com/ae.svg",
  currency: "AED",
  currency_name: "United Arab Emirates dirham",
  currency_symbol: "د.إ",
};

export const COUNTRY: ICountry[] = [
  {
    name: "Afghanistan",
    code: "AF",
    country_code: "AFG",
    dial_code: "+93",
    flag: "https://flagcdn.com/af.svg",
    currency: "AFN",
    currency_name: "Afghan afghani",
    currency_symbol: "؋",
  },
  {
    name: "Åland Islands",
    code: "AX",
    country_code: "ALA",
    dial_code: "+35818",
    flag: "https://flagcdn.com/ax.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Albania",
    code: "AL",
    country_code: "ALB",
    dial_code: "+355",
    flag: "https://flagcdn.com/al.svg",
    currency: "ALL",
    currency_name: "Albanian lek",
    currency_symbol: "L",
  },
  {
    name: "Algeria",
    code: "DZ",
    country_code: "DZA",
    dial_code: "+213",
    flag: "https://flagcdn.com/dz.svg",
    currency: "DZD",
    currency_name: "Algerian dinar",
    currency_symbol: "د.ج",
  },
  {
    name: "American Samoa",
    code: "AS",
    country_code: "ASM",
    dial_code: "+1684",
    flag: "https://flagcdn.com/as.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Andorra",
    code: "AD",
    country_code: "AND",
    dial_code: "+376",
    flag: "https://flagcdn.com/ad.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Angola",
    code: "AO",
    country_code: "AGO",
    dial_code: "+244",
    flag: "https://flagcdn.com/ao.svg",
    currency: "AOA",
    currency_name: "Angolan kwanza",
    currency_symbol: "Kz",
  },
  {
    name: "Anguilla",
    code: "AI",
    country_code: "AIA",
    dial_code: "+1264",
    flag: "https://flagcdn.com/ai.svg",
    currency: "XCD",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Antarctica",
    code: "AQ",
    country_code: "ATA",
    dial_code: "N/A",
    flag: "https://flagcdn.com/aq.svg",
    currency: "N/A",
    currency_name: "N/A",
    currency_symbol: "N/A",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    country_code: "ATG",
    dial_code: "+1268",
    flag: "https://flagcdn.com/ag.svg",
    currency: "XCD",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Argentina",
    code: "AR",
    country_code: "ARG",
    dial_code: "+54",
    flag: "https://flagcdn.com/ar.svg",
    currency: "ARS",
    currency_name: "Argentine peso",
    currency_symbol: "$",
  },
  {
    name: "Armenia",
    code: "AM",
    country_code: "ARM",
    dial_code: "+374",
    flag: "https://flagcdn.com/am.svg",
    currency: "AMD",
    currency_name: "Armenian dram",
    currency_symbol: "֏",
  },
  {
    name: "Aruba",
    code: "AW",
    country_code: "ABW",
    dial_code: "+297",
    flag: "https://flagcdn.com/aw.svg",
    currency: "AWG",
    currency_name: "Aruban florin",
    currency_symbol: "ƒ",
  },
  {
    name: "Australia",
    code: "AU",
    country_code: "AUS",
    dial_code: "+61",
    flag: "https://flagcdn.com/au.svg",
    currency: "AUD",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "Austria",
    code: "AT",
    country_code: "AUT",
    dial_code: "+43",
    flag: "https://flagcdn.com/at.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    country_code: "AZE",
    dial_code: "+994",
    flag: "https://flagcdn.com/az.svg",
    currency: "AZN",
    currency_name: "Azerbaijani manat",
    currency_symbol: "₼",
  },
  {
    name: "Bahamas",
    code: "BS",
    country_code: "BHS",
    dial_code: "+1242",
    flag: "https://flagcdn.com/bs.svg",
    currency: "BSD",
    currency_name: "Bahamian dollar",
    currency_symbol: "$",
  },
  {
    name: "Bahrain",
    code: "BH",
    country_code: "BHR",
    dial_code: "+973",
    flag: "https://flagcdn.com/bh.svg",
    currency: "BHD",
    currency_name: "Bahraini dinar",
    currency_symbol: ".د.ب",
  },
  {
    name: "Bangladesh",
    code: "BD",
    country_code: "BGD",
    dial_code: "+880",
    flag: "https://flagcdn.com/bd.svg",
    currency: "BDT",
    currency_name: "Bangladeshi taka",
    currency_symbol: "৳",
  },
  {
    name: "Barbados",
    code: "BB",
    country_code: "BRB",
    dial_code: "+1246",
    flag: "https://flagcdn.com/bb.svg",
    currency: "BBD",
    currency_name: "Barbadian dollar",
    currency_symbol: "$",
  },
  {
    name: "Belarus",
    code: "BY",
    country_code: "BLR",
    dial_code: "+375",
    flag: "https://flagcdn.com/by.svg",
    currency: "BYN",
    currency_name: "Belarusian ruble",
    currency_symbol: "Br",
  },
  {
    name: "Belgium",
    code: "BE",
    country_code: "BEL",
    dial_code: "+32",
    flag: "https://flagcdn.com/be.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Belize",
    code: "BZ",
    country_code: "BLZ",
    dial_code: "+501",
    flag: "https://flagcdn.com/bz.svg",
    currency: "BZD",
    currency_name: "Belize dollar",
    currency_symbol: "$",
  },
  {
    name: "Benin",
    code: "BJ",
    country_code: "BEN",
    dial_code: "+229",
    flag: "https://flagcdn.com/bj.svg",
    currency: "XOF",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Bermuda",
    code: "BM",
    country_code: "BMU",
    dial_code: "+1441",
    flag: "https://flagcdn.com/bm.svg",
    currency: "BMD",
    currency_name: "Bermudian dollar",
    currency_symbol: "$",
  },
  {
    name: "Bhutan",
    code: "BT",
    country_code: "BTN",
    dial_code: "+975",
    flag: "https://flagcdn.com/bt.svg",
    currency: "BTN",
    currency_name: "Bhutanese ngultrum",
    currency_symbol: "Nu.",
  },
  {
    name: "Bolivia",
    code: "BO",
    country_code: "BOL",
    dial_code: "+591",
    flag: "https://flagcdn.com/bo.svg",
    currency: "BOB",
    currency_name: "Bolivian boliviano",
    currency_symbol: "Bs.",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    country_code: "BIH",
    dial_code: "+387",
    flag: "https://flagcdn.com/ba.svg",
    currency: "BAM",
    currency_name: "Bosnia and Herzegovina convertible mark",
    currency_symbol: "KM",
  },
  {
    name: "Botswana",
    code: "BW",
    country_code: "BWA",
    dial_code: "+267",
    flag: "https://flagcdn.com/bw.svg",
    currency: "BWP",
    currency_name: "Botswana pula",
    currency_symbol: "P",
  },
  {
    name: "Bouvet Island",
    code: "BV",
    country_code: "BVT",
    dial_code: "+47",
    flag: "https://flagcdn.com/bv.svg",
    currency: "N/A",
    currency_name: "N/A",
    currency_symbol: "N/A",
  },
  {
    name: "Brazil",
    code: "BR",
    country_code: "BRA",
    dial_code: "+55",
    flag: "https://flagcdn.com/br.svg",
    currency: "BRL",
    currency_name: "Brazilian real",
    currency_symbol: "R$",
  },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    country_code: "IOT",
    dial_code: "+246",
    flag: "https://flagcdn.com/io.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "British Virgin Islands",
    code: "VG",
    country_code: "VGB",
    dial_code: "+1284",
    flag: "https://flagcdn.com/vg.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Brunei",
    code: "BN",
    country_code: "BRN",
    dial_code: "+673",
    flag: "https://flagcdn.com/bn.svg",
    currency: "BND",
    currency_name: "Brunei dollar",
    currency_symbol: "$",
  },
  {
    name: "Bulgaria",
    code: "BG",
    country_code: "BGR",
    dial_code: "+359",
    flag: "https://flagcdn.com/bg.svg",
    currency: "BGN",
    currency_name: "Bulgarian lev",
    currency_symbol: "лв",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    country_code: "BFA",
    dial_code: "+226",
    flag: "https://flagcdn.com/bf.svg",
    currency: "XOF",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Burundi",
    code: "BI",
    country_code: "BDI",
    dial_code: "+257",
    flag: "https://flagcdn.com/bi.svg",
    currency: "BIF",
    currency_name: "Burundian franc",
    currency_symbol: "Fr",
  },
  {
    name: "Cambodia",
    code: "KH",
    country_code: "KHM",
    dial_code: "+855",
    flag: "https://flagcdn.com/kh.svg",
    currency: "KHR",
    currency_name: "Cambodian riel",
    currency_symbol: "៛",
  },
  {
    name: "Cameroon",
    code: "CM",
    country_code: "CMR",
    dial_code: "+237",
    flag: "https://flagcdn.com/cm.svg",
    currency: "XAF",
    currency_name: "Central African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Canada",
    code: "CA",
    country_code: "CAN",
    dial_code: "+1",
    flag: "https://flagcdn.com/ca.svg",
    currency: "CAD",
    currency_name: "Canadian dollar",
    currency_symbol: "$",
  },
  {
    name: "Cape Verde",
    code: "CV",
    country_code: "CPV",
    dial_code: "+238",
    flag: "https://flagcdn.com/cv.svg",
    currency: "CVE",
    currency_name: "Cape Verdean escudo",
    currency_symbol: "Esc",
  },
  {
    name: "Caribbean Netherlands",
    code: "BQ",
    country_code: "BES",
    dial_code: "+599",
    flag: "https://flagcdn.com/bq.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    country_code: "CYM",
    dial_code: "+1345",
    flag: "https://flagcdn.com/ky.svg",
    currency: "KYD",
    currency_name: "Cayman Islands dollar",
    currency_symbol: "$",
  },
  {
    name: "Central African Republic",
    code: "CF",
    country_code: "CAF",
    dial_code: "+236",
    flag: "https://flagcdn.com/cf.svg",
    currency: "XAF",
    currency_name: "Central African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Chad",
    code: "TD",
    country_code: "TCD",
    dial_code: "+235",
    flag: "https://flagcdn.com/td.svg",
    currency: "XAF",
    currency_name: "Central African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Chile",
    code: "CL",
    country_code: "CHL",
    dial_code: "+56",
    flag: "https://flagcdn.com/cl.svg",
    currency: "CLP",
    currency_name: "Chilean peso",
    currency_symbol: "$",
  },
  {
    name: "China",
    code: "CN",
    country_code: "CHN",
    dial_code: "+86",
    flag: "https://flagcdn.com/cn.svg",
    currency: "CNY",
    currency_name: "Chinese yuan",
    currency_symbol: "¥",
  },
  {
    name: "Christmas Island",
    code: "CX",
    country_code: "CXR",
    dial_code: "+61",
    flag: "https://flagcdn.com/cx.svg",
    currency: "AUD",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    country_code: "CCK",
    dial_code: "+61",
    flag: "https://flagcdn.com/cc.svg",
    currency: "AUD",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "Colombia",
    code: "CO",
    country_code: "COL",
    dial_code: "+57",
    flag: "https://flagcdn.com/co.svg",
    currency: "COP",
    currency_name: "Colombian peso",
    currency_symbol: "$",
  },
  {
    name: "Comoros",
    code: "KM",
    country_code: "COM",
    dial_code: "+269",
    flag: "https://flagcdn.com/km.svg",
    currency: "KMF",
    currency_name: "Comorian franc",
    currency_symbol: "Fr",
  },
  {
    name: "Cook Islands",
    code: "CK",
    country_code: "COK",
    dial_code: "+682",
    flag: "https://flagcdn.com/ck.svg",
    currency: "CKD",
    currency_name: "Cook Islands dollar",
    currency_symbol: "$",
  },
  {
    name: "Costa Rica",
    code: "CR",
    country_code: "CRI",
    dial_code: "+506",
    flag: "https://flagcdn.com/cr.svg",
    currency: "CRC",
    currency_name: "Costa Rican colón",
    currency_symbol: "₡",
  },
  {
    name: "Croatia",
    code: "HR",
    country_code: "HRV",
    dial_code: "+385",
    flag: "https://flagcdn.com/hr.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Cuba",
    code: "CU",
    country_code: "CUB",
    dial_code: "+53",
    flag: "https://flagcdn.com/cu.svg",
    currency: "CUC",
    currency_name: "Cuban convertible peso",
    currency_symbol: "$",
  },
  {
    name: "Curaçao",
    code: "CW",
    country_code: "CUW",
    dial_code: "+599",
    flag: "https://flagcdn.com/cw.svg",
    currency: "ANG",
    currency_name: "Netherlands Antillean guilder",
    currency_symbol: "ƒ",
  },
  {
    name: "Cyprus",
    code: "CY",
    country_code: "CYP",
    dial_code: "+357",
    flag: "https://flagcdn.com/cy.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Czechia",
    code: "CZ",
    country_code: "CZE",
    dial_code: "+420",
    flag: "https://flagcdn.com/cz.svg",
    currency: "CZK",
    currency_name: "Czech koruna",
    currency_symbol: "Kč",
  },
  {
    name: "Denmark",
    code: "DK",
    country_code: "DNK",
    dial_code: "+45",
    flag: "https://flagcdn.com/dk.svg",
    currency: "DKK",
    currency_name: "Danish krone",
    currency_symbol: "kr",
  },
  {
    name: "Djibouti",
    code: "DJ",
    country_code: "DJI",
    dial_code: "+253",
    flag: "https://flagcdn.com/dj.svg",
    currency: "DJF",
    currency_name: "Djiboutian franc",
    currency_symbol: "Fr",
  },
  {
    name: "Dominica",
    code: "DM",
    country_code: "DMA",
    dial_code: "+1767",
    flag: "https://flagcdn.com/dm.svg",
    currency: "XCD",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    country_code: "DOM",
    dial_code: "+1809",
    flag: "https://flagcdn.com/do.svg",
    currency: "DOP",
    currency_name: "Dominican peso",
    currency_symbol: "$",
  },
  {
    name: "DR Congo",
    code: "CD",
    country_code: "COD",
    dial_code: "+243",
    flag: "https://flagcdn.com/cd.svg",
    currency: "CDF",
    currency_name: "Congolese franc",
    currency_symbol: "FC",
  },
  {
    name: "Ecuador",
    code: "EC",
    country_code: "ECU",
    dial_code: "+593",
    flag: "https://flagcdn.com/ec.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Egypt",
    code: "EG",
    country_code: "EGY",
    dial_code: "+20",
    flag: "https://flagcdn.com/eg.svg",
    currency: "EGP",
    currency_name: "Egyptian pound",
    currency_symbol: "£",
  },
  {
    name: "El Salvador",
    code: "SV",
    country_code: "SLV",
    dial_code: "+503",
    flag: "https://flagcdn.com/sv.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    country_code: "GNQ",
    dial_code: "+240",
    flag: "https://flagcdn.com/gq.svg",
    currency: "XAF",
    currency_name: "Central African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Eritrea",
    code: "ER",
    country_code: "ERI",
    dial_code: "+291",
    flag: "https://flagcdn.com/er.svg",
    currency: "ERN",
    currency_name: "Eritrean nakfa",
    currency_symbol: "Nfk",
  },
  {
    name: "Estonia",
    code: "EE",
    country_code: "EST",
    dial_code: "+372",
    flag: "https://flagcdn.com/ee.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Eswatini",
    code: "SZ",
    country_code: "SWZ",
    dial_code: "+268",
    flag: "https://flagcdn.com/sz.svg",
    currency: "SZL",
    currency_name: "Swazi lilangeni",
    currency_symbol: "L",
  },
  {
    name: "Ethiopia",
    code: "ET",
    country_code: "ETH",
    dial_code: "+251",
    flag: "https://flagcdn.com/et.svg",
    currency: "ETB",
    currency_name: "Ethiopian birr",
    currency_symbol: "Br",
  },
  {
    name: "Falkland Islands",
    code: "FK",
    country_code: "FLK",
    dial_code: "+500",
    flag: "https://flagcdn.com/fk.svg",
    currency: "FKP",
    currency_name: "Falkland Islands pound",
    currency_symbol: "£",
  },
  {
    name: "Faroe Islands",
    code: "FO",
    country_code: "FRO",
    dial_code: "+298",
    flag: "https://flagcdn.com/fo.svg",
    currency: "DKK",
    currency_name: "Danish krone",
    currency_symbol: "kr",
  },
  {
    name: "Fiji",
    code: "FJ",
    country_code: "FJI",
    dial_code: "+679",
    flag: "https://flagcdn.com/fj.svg",
    currency: "FJD",
    currency_name: "Fijian dollar",
    currency_symbol: "$",
  },
  {
    name: "Finland",
    code: "FI",
    country_code: "FIN",
    dial_code: "+358",
    flag: "https://flagcdn.com/fi.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "France",
    code: "FR",
    country_code: "FRA",
    dial_code: "+33",
    flag: "https://flagcdn.com/fr.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "French Guiana",
    code: "GF",
    country_code: "GUF",
    dial_code: "+594",
    flag: "https://flagcdn.com/gf.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "French Polynesia",
    code: "PF",
    country_code: "PYF",
    dial_code: "+689",
    flag: "https://flagcdn.com/pf.svg",
    currency: "XPF",
    currency_name: "CFP franc",
    currency_symbol: "₣",
  },
  {
    name: "French Southern and Antarctic Lands",
    code: "TF",
    country_code: "ATF",
    dial_code: "+262",
    flag: "https://flagcdn.com/tf.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Gabon",
    code: "GA",
    country_code: "GAB",
    dial_code: "+241",
    flag: "https://flagcdn.com/ga.svg",
    currency: "XAF",
    currency_name: "Central African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Gambia",
    code: "GM",
    country_code: "GMB",
    dial_code: "+220",
    flag: "https://flagcdn.com/gm.svg",
    currency: "GMD",
    currency_name: "dalasi",
    currency_symbol: "D",
  },
  {
    name: "Georgia",
    code: "GE",
    country_code: "GEO",
    dial_code: "+995",
    flag: "https://flagcdn.com/ge.svg",
    currency: "GEL",
    currency_name: "lari",
    currency_symbol: "₾",
  },
  {
    name: "Germany",
    code: "DE",
    country_code: "DEU",
    dial_code: "+49",
    flag: "https://flagcdn.com/de.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Ghana",
    code: "GH",
    country_code: "GHA",
    dial_code: "+233",
    flag: "https://flagcdn.com/gh.svg",
    currency: "GHS",
    currency_name: "Ghanaian cedi",
    currency_symbol: "₵",
  },
  {
    name: "Gibraltar",
    code: "GI",
    country_code: "GIB",
    dial_code: "+350",
    flag: "https://flagcdn.com/gi.svg",
    currency: "GIP",
    currency_name: "Gibraltar pound",
    currency_symbol: "£",
  },
  {
    name: "Greece",
    code: "GR",
    country_code: "GRC",
    dial_code: "+30",
    flag: "https://flagcdn.com/gr.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Greenland",
    code: "GL",
    country_code: "GRL",
    dial_code: "+299",
    flag: "https://flagcdn.com/gl.svg",
    currency: "DKK",
    currency_name: "krone",
    currency_symbol: "kr.",
  },
  {
    name: "Grenada",
    code: "GD",
    country_code: "GRD",
    dial_code: "+1473",
    flag: "https://flagcdn.com/gd.svg",
    currency: "XCD",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Guadeloupe",
    code: "GP",
    country_code: "GLP",
    dial_code: "+590",
    flag: "https://flagcdn.com/gp.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Guam",
    code: "GU",
    country_code: "GUM",
    dial_code: "+1671",
    flag: "https://flagcdn.com/gu.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Guatemala",
    code: "GT",
    country_code: "GTM",
    dial_code: "+502",
    flag: "https://flagcdn.com/gt.svg",
    currency: "GTQ",
    currency_name: "Guatemalan quetzal",
    currency_symbol: "Q",
  },
  {
    name: "Guernsey",
    code: "GG",
    country_code: "GGY",
    dial_code: "+44",
    flag: "https://flagcdn.com/gg.svg",
    currency: "GBP",
    currency_name: "British pound",
    currency_symbol: "£",
  },
  {
    name: "Guinea",
    code: "GN",
    country_code: "GIN",
    dial_code: "+224",
    flag: "https://flagcdn.com/gn.svg",
    currency: "GNF",
    currency_name: "Guinean franc",
    currency_symbol: "Fr",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    country_code: "GNB",
    dial_code: "+245",
    flag: "https://flagcdn.com/gw.svg",
    currency: "XOF",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Guyana",
    code: "GY",
    country_code: "GUY",
    dial_code: "+592",
    flag: "https://flagcdn.com/gy.svg",
    currency: "GYD",
    currency_name: "Guyanese dollar",
    currency_symbol: "$",
  },
  {
    name: "Haiti",
    code: "HT",
    country_code: "HTI",
    dial_code: "+509",
    flag: "https://flagcdn.com/ht.svg",
    currency: "HTG",
    currency_name: "Haitian gourde",
    currency_symbol: "G",
  },
  {
    name: "Heard Island and McDonald Islands",
    code: "HM",
    country_code: "HMD",
    dial_code: "N/A",
    flag: "https://flagcdn.com/hm.svg",
    currency: "N/A",
    currency_name: "N/A",
    currency_symbol: "N/A",
  },
  {
    name: "Honduras",
    code: "HN",
    country_code: "HND",
    dial_code: "+504",
    flag: "https://flagcdn.com/hn.svg",
    currency: "HNL",
    currency_name: "Honduran lempira",
    currency_symbol: "L",
  },
  {
    name: "Hong Kong",
    code: "HK",
    country_code: "HKG",
    dial_code: "+852",
    flag: "https://flagcdn.com/hk.svg",
    currency: "HKD",
    currency_name: "Hong Kong dollar",
    currency_symbol: "$",
  },
  {
    name: "Hungary",
    code: "HU",
    country_code: "HUN",
    dial_code: "+36",
    flag: "https://flagcdn.com/hu.svg",
    currency: "HUF",
    currency_name: "Hungarian forint",
    currency_symbol: "Ft",
  },
  {
    name: "Iceland",
    code: "IS",
    country_code: "ISL",
    dial_code: "+354",
    flag: "https://flagcdn.com/is.svg",
    currency: "ISK",
    currency_name: "Icelandic króna",
    currency_symbol: "kr",
  },
  {
    name: "India",
    code: "IN",
    country_code: "IND",
    dial_code: "+91",
    flag: "https://flagcdn.com/in.svg",
    currency: "INR",
    currency_name: "Indian rupee",
    currency_symbol: "₹",
  },
  {
    name: "Indonesia",
    code: "ID",
    country_code: "IDN",
    dial_code: "+62",
    flag: "https://flagcdn.com/id.svg",
    currency: "IDR",
    currency_name: "Indonesian rupiah",
    currency_symbol: "Rp",
  },
  {
    name: "Iran",
    code: "IR",
    country_code: "IRN",
    dial_code: "+98",
    flag: "https://flagcdn.com/ir.svg",
    currency: "IRR",
    currency_name: "Iranian rial",
    currency_symbol: "﷼",
  },
  {
    name: "Iraq",
    code: "IQ",
    country_code: "IRQ",
    dial_code: "+964",
    flag: "https://flagcdn.com/iq.svg",
    currency: "IQD",
    currency_name: "Iraqi dinar",
    currency_symbol: "ع.د",
  },
  {
    name: "Ireland",
    code: "IE",
    country_code: "IRL",
    dial_code: "+353",
    flag: "https://flagcdn.com/ie.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Isle of Man",
    code: "IM",
    country_code: "IMN",
    dial_code: "+44",
    flag: "https://flagcdn.com/im.svg",
    currency: "GBP",
    currency_name: "British pound",
    currency_symbol: "£",
  },
  {
    name: "Israel",
    code: "IL",
    country_code: "ISR",
    dial_code: "+972",
    flag: "https://flagcdn.com/il.svg",
    currency: "ILS",
    currency_name: "Israeli new shekel",
    currency_symbol: "₪",
  },
  {
    name: "Italy",
    code: "IT",
    country_code: "ITA",
    dial_code: "+39",
    flag: "https://flagcdn.com/it.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Ivory Coast",
    code: "CI",
    country_code: "CIV",
    dial_code: "+225",
    flag: "https://flagcdn.com/ci.svg",
    currency: "XOF",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Jamaica",
    code: "JM",
    country_code: "JAM",
    dial_code: "+1876",
    flag: "https://flagcdn.com/jm.svg",
    currency: "JMD",
    currency_name: "Jamaican dollar",
    currency_symbol: "$",
  },
  {
    name: "Japan",
    code: "JP",
    country_code: "JPN",
    dial_code: "+81",
    flag: "https://flagcdn.com/jp.svg",
    currency: "JPY",
    currency_name: "Japanese yen",
    currency_symbol: "¥",
  },
  {
    name: "Jersey",
    code: "JE",
    country_code: "JEY",
    dial_code: "+44",
    flag: "https://flagcdn.com/je.svg",
    currency: "GBP",
    currency_name: "British pound",
    currency_symbol: "£",
  },
  {
    name: "Jordan",
    code: "JO",
    country_code: "JOR",
    dial_code: "+962",
    flag: "https://flagcdn.com/jo.svg",
    currency: "JOD",
    currency_name: "Jordanian dinar",
    currency_symbol: "د.ا",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    country_code: "KAZ",
    dial_code: "+76",
    flag: "https://flagcdn.com/kz.svg",
    currency: "KZT",
    currency_name: "Kazakhstani tenge",
    currency_symbol: "₸",
  },
  {
    name: "Kenya",
    code: "KE",
    country_code: "KEN",
    dial_code: "+254",
    flag: "https://flagcdn.com/ke.svg",
    currency: "KES",
    currency_name: "Kenyan shilling",
    currency_symbol: "Sh",
  },
  {
    name: "Kiribati",
    code: "KI",
    country_code: "KIR",
    dial_code: "+686",
    flag: "https://flagcdn.com/ki.svg",
    currency: "AUD",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "Kosovo",
    code: "XK",
    country_code: "UNK",
    dial_code: "+383",
    flag: "https://flagcdn.com/xk.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Kuwait",
    code: "KW",
    country_code: "KWT",
    dial_code: "+965",
    flag: "https://flagcdn.com/kw.svg",
    currency: "KWD",
    currency_name: "Kuwaiti dinar",
    currency_symbol: "د.ك",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    country_code: "KGZ",
    dial_code: "+996",
    flag: "https://flagcdn.com/kg.svg",
    currency: "KGS",
    currency_name: "Kyrgyzstani som",
    currency_symbol: "с",
  },
  {
    name: "Laos",
    code: "LA",
    country_code: "LAO",
    dial_code: "+856",
    flag: "https://flagcdn.com/la.svg",
    currency: "LAK",
    currency_name: "Lao kip",
    currency_symbol: "₭",
  },
  {
    name: "Latvia",
    code: "LV",
    country_code: "LVA",
    dial_code: "+371",
    flag: "https://flagcdn.com/lv.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Lebanon",
    code: "LB",
    country_code: "LBN",
    dial_code: "+961",
    flag: "https://flagcdn.com/lb.svg",
    currency: "LBP",
    currency_name: "Lebanese pound",
    currency_symbol: "ل.ل",
  },
  {
    name: "Lesotho",
    code: "LS",
    country_code: "LSO",
    dial_code: "+266",
    flag: "https://flagcdn.com/ls.svg",
    currency: "LSL",
    currency_name: "Lesotho loti",
    currency_symbol: "L",
  },
  {
    name: "Liberia",
    code: "LR",
    country_code: "LBR",
    dial_code: "+231",
    flag: "https://flagcdn.com/lr.svg",
    currency: "LRD",
    currency_name: "Liberian dollar",
    currency_symbol: "$",
  },
  {
    name: "Libya",
    code: "LY",
    country_code: "LBY",
    dial_code: "+218",
    flag: "https://flagcdn.com/ly.svg",
    currency: "LYD",
    currency_name: "Libyan dinar",
    currency_symbol: "ل.د",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    country_code: "LIE",
    dial_code: "+423",
    flag: "https://flagcdn.com/li.svg",
    currency: "CHF",
    currency_name: "Swiss franc",
    currency_symbol: "Fr",
  },
  {
    name: "Lithuania",
    code: "LT",
    country_code: "LTU",
    dial_code: "+370",
    flag: "https://flagcdn.com/lt.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Luxembourg",
    code: "LU",
    country_code: "LUX",
    dial_code: "+352",
    flag: "https://flagcdn.com/lu.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Macau",
    code: "MO",
    country_code: "MAC",
    dial_code: "+853",
    flag: "https://flagcdn.com/mo.svg",
    currency: "MOP",
    currency_name: "Macanese pataca",
    currency_symbol: "P",
  },
  {
    name: "Madagascar",
    code: "MG",
    country_code: "MDG",
    dial_code: "+261",
    flag: "https://flagcdn.com/mg.svg",
    currency: "MGA",
    currency_name: "Malagasy ariary",
    currency_symbol: "Ar",
  },
  {
    name: "Malawi",
    code: "MW",
    country_code: "MWI",
    dial_code: "+265",
    flag: "https://flagcdn.com/mw.svg",
    currency: "MWK",
    currency_name: "Malawian kwacha",
    currency_symbol: "MK",
  },
  {
    name: "Malaysia",
    code: "MY",
    country_code: "MYS",
    dial_code: "+60",
    flag: "https://flagcdn.com/my.svg",
    currency: "MYR",
    currency_name: "Malaysian ringgit",
    currency_symbol: "RM",
  },
  {
    name: "Maldives",
    code: "MV",
    country_code: "MDV",
    dial_code: "+960",
    flag: "https://flagcdn.com/mv.svg",
    currency: "MVR",
    currency_name: "Maldivian rufiyaa",
    currency_symbol: ".ރ",
  },
  {
    name: "Mali",
    code: "ML",
    country_code: "MLI",
    dial_code: "+223",
    flag: "https://flagcdn.com/ml.svg",
    currency: "XOF",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Malta",
    code: "MT",
    country_code: "MLT",
    dial_code: "+356",
    flag: "https://flagcdn.com/mt.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    country_code: "MHL",
    dial_code: "+692",
    flag: "https://flagcdn.com/mh.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Martinique",
    code: "MQ",
    country_code: "MTQ",
    dial_code: "+596",
    flag: "https://flagcdn.com/mq.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Mauritania",
    code: "MR",
    country_code: "MRT",
    dial_code: "+222",
    flag: "https://flagcdn.com/mr.svg",
    currency: "MRU",
    currency_name: "Mauritanian ouguiya",
    currency_symbol: "UM",
  },
  {
    name: "Mauritius",
    code: "MU",
    country_code: "MUS",
    dial_code: "+230",
    flag: "https://flagcdn.com/mu.svg",
    currency: "MUR",
    currency_name: "Mauritian rupee",
    currency_symbol: "₨",
  },
  {
    name: "Mayotte",
    code: "YT",
    country_code: "MYT",
    dial_code: "+262",
    flag: "https://flagcdn.com/yt.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Mexico",
    code: "MX",
    country_code: "MEX",
    dial_code: "+52",
    flag: "https://flagcdn.com/mx.svg",
    currency: "MXN",
    currency_name: "Mexican peso",
    currency_symbol: "$",
  },
  {
    name: "Micronesia",
    code: "FM",
    country_code: "FSM",
    dial_code: "+691",
    flag: "https://flagcdn.com/fm.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Moldova",
    code: "MD",
    country_code: "MDA",
    dial_code: "+373",
    flag: "https://flagcdn.com/md.svg",
    currency: "MDL",
    currency_name: "Moldovan leu",
    currency_symbol: "L",
  },
  {
    name: "Monaco",
    code: "MC",
    country_code: "MCO",
    dial_code: "+377",
    flag: "https://flagcdn.com/mc.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Mongolia",
    code: "MN",
    country_code: "MNG",
    dial_code: "+976",
    flag: "https://flagcdn.com/mn.svg",
    currency: "MNT",
    currency_name: "Mongolian tögrög",
    currency_symbol: "₮",
  },
  {
    name: "Montenegro",
    code: "ME",
    country_code: "MNE",
    dial_code: "+382",
    flag: "https://flagcdn.com/me.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Montserrat",
    code: "MS",
    country_code: "MSR",
    dial_code: "+1664",
    flag: "https://flagcdn.com/ms.svg",
    currency: "XCD",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Morocco",
    code: "MA",
    country_code: "MAR",
    dial_code: "+212",
    flag: "https://flagcdn.com/ma.svg",
    currency: "MAD",
    currency_name: "Moroccan dirham",
    currency_symbol: "د.م.",
  },
  {
    name: "Mozambique",
    code: "MZ",
    country_code: "MOZ",
    dial_code: "+258",
    flag: "https://flagcdn.com/mz.svg",
    currency: "MZN",
    currency_name: "Mozambican metical",
    currency_symbol: "MT",
  },
  {
    name: "Myanmar",
    code: "MM",
    country_code: "MMR",
    dial_code: "+95",
    flag: "https://flagcdn.com/mm.svg",
    currency: "MMK",
    currency_name: "Burmese kyat",
    currency_symbol: "Ks",
  },
  {
    name: "Namibia",
    code: "NA",
    country_code: "NAM",
    dial_code: "+264",
    flag: "https://flagcdn.com/na.svg",
    currency: "NAD",
    currency_name: "Namibian dollar",
    currency_symbol: "$",
  },
  {
    name: "Nauru",
    code: "NR",
    country_code: "NRU",
    dial_code: "+674",
    flag: "https://flagcdn.com/nr.svg",
    currency: "AUD",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "Nepal",
    code: "NP",
    country_code: "NPL",
    dial_code: "+977",
    flag: "https://flagcdn.com/np.svg",
    currency: "NPR",
    currency_name: "Nepalese rupee",
    currency_symbol: "₨",
  },
  {
    name: "Netherlands",
    code: "NL",
    country_code: "NLD",
    dial_code: "+31",
    flag: "https://flagcdn.com/nl.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "New Caledonia",
    code: "NC",
    country_code: "NCL",
    dial_code: "+687",
    flag: "https://flagcdn.com/nc.svg",
    currency: "XPF",
    currency_name: "CFP franc",
    currency_symbol: "₣",
  },
  {
    name: "New Zealand",
    code: "NZ",
    country_code: "NZL",
    dial_code: "+64",
    flag: "https://flagcdn.com/nz.svg",
    currency: "NZD",
    currency_name: "New Zealand dollar",
    currency_symbol: "$",
  },
  {
    name: "Nicaragua",
    code: "NI",
    country_code: "NIC",
    dial_code: "+505",
    flag: "https://flagcdn.com/ni.svg",
    currency: "NIO",
    currency_name: "Nicaraguan córdoba",
    currency_symbol: "C$",
  },
  {
    name: "Niger",
    code: "NE",
    country_code: "NER",
    dial_code: "+227",
    flag: "https://flagcdn.com/ne.svg",
    currency: "XOF",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Nigeria",
    code: "NG",
    country_code: "NGA",
    dial_code: "+234",
    flag: "https://flagcdn.com/ng.svg",
    currency: "NGN",
    currency_name: "Nigerian naira",
    currency_symbol: "₦",
  },
  {
    name: "Niue",
    code: "NU",
    country_code: "NIU",
    dial_code: "+683",
    flag: "https://flagcdn.com/nu.svg",
    currency: "NZD",
    currency_name: "New Zealand dollar",
    currency_symbol: "$",
  },
  {
    name: "Norfolk Island",
    code: "NF",
    country_code: "NFK",
    dial_code: "+672",
    flag: "https://flagcdn.com/nf.svg",
    currency: "AUD",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "North Korea",
    code: "KP",
    country_code: "PRK",
    dial_code: "+850",
    flag: "https://flagcdn.com/kp.svg",
    currency: "KPW",
    currency_name: "North Korean won",
    currency_symbol: "₩",
  },
  {
    name: "North Macedonia",
    code: "MK",
    country_code: "MKD",
    dial_code: "+389",
    flag: "https://flagcdn.com/mk.svg",
    currency: "MKD",
    currency_name: "denar",
    currency_symbol: "den",
  },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    country_code: "MNP",
    dial_code: "+1670",
    flag: "https://flagcdn.com/mp.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Norway",
    code: "NO",
    country_code: "NOR",
    dial_code: "+47",
    flag: "https://flagcdn.com/no.svg",
    currency: "NOK",
    currency_name: "Norwegian krone",
    currency_symbol: "kr",
  },
  {
    name: "Oman",
    code: "OM",
    country_code: "OMN",
    dial_code: "+968",
    flag: "https://flagcdn.com/om.svg",
    currency: "OMR",
    currency_name: "Omani rial",
    currency_symbol: "ر.ع.",
  },
  {
    name: "Pakistan",
    code: "PK",
    country_code: "PAK",
    dial_code: "+92",
    flag: "https://flagcdn.com/pk.svg",
    currency: "PKR",
    currency_name: "Pakistani rupee",
    currency_symbol: "₨",
  },
  {
    name: "Palau",
    code: "PW",
    country_code: "PLW",
    dial_code: "+680",
    flag: "https://flagcdn.com/pw.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Palestine",
    code: "PS",
    country_code: "PSE",
    dial_code: "+970",
    flag: "https://flagcdn.com/ps.svg",
    currency: "EGP",
    currency_name: "Egyptian pound",
    currency_symbol: "E£",
  },
  {
    name: "Panama",
    code: "PA",
    country_code: "PAN",
    dial_code: "+507",
    flag: "https://flagcdn.com/pa.svg",
    currency: "PAB",
    currency_name: "Panamanian balboa",
    currency_symbol: "B/.",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    country_code: "PNG",
    dial_code: "+675",
    flag: "https://flagcdn.com/pg.svg",
    currency: "PGK",
    currency_name: "Papua New Guinean kina",
    currency_symbol: "K",
  },
  {
    name: "Paraguay",
    code: "PY",
    country_code: "PRY",
    dial_code: "+595",
    flag: "https://flagcdn.com/py.svg",
    currency: "PYG",
    currency_name: "Paraguayan guaraní",
    currency_symbol: "₲",
  },
  {
    name: "Peru",
    code: "PE",
    country_code: "PER",
    dial_code: "+51",
    flag: "https://flagcdn.com/pe.svg",
    currency: "PEN",
    currency_name: "Peruvian sol",
    currency_symbol: "S/ ",
  },
  {
    name: "Philippines",
    code: "PH",
    country_code: "PHL",
    dial_code: "+63",
    flag: "https://flagcdn.com/ph.svg",
    currency: "PHP",
    currency_name: "Philippine peso",
    currency_symbol: "₱",
  },
  {
    name: "Pitcairn Islands",
    code: "PN",
    country_code: "PCN",
    dial_code: "+64",
    flag: "https://flagcdn.com/pn.svg",
    currency: "NZD",
    currency_name: "New Zealand dollar",
    currency_symbol: "$",
  },
  {
    name: "Poland",
    code: "PL",
    country_code: "POL",
    dial_code: "+48",
    flag: "https://flagcdn.com/pl.svg",
    currency: "PLN",
    currency_name: "Polish złoty",
    currency_symbol: "zł",
  },
  {
    name: "Portugal",
    code: "PT",
    country_code: "PRT",
    dial_code: "+351",
    flag: "https://flagcdn.com/pt.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    country_code: "PRI",
    dial_code: "+1787",
    flag: "https://flagcdn.com/pr.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Qatar",
    code: "QA",
    country_code: "QAT",
    dial_code: "+974",
    flag: "https://flagcdn.com/qa.svg",
    currency: "QAR",
    currency_name: "Qatari riyal",
    currency_symbol: "ر.ق",
  },
  {
    name: "Republic of the Congo",
    code: "CG",
    country_code: "COG",
    dial_code: "+242",
    flag: "https://flagcdn.com/cg.svg",
    currency: "XAF",
    currency_name: "Central African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Réunion",
    code: "RE",
    country_code: "REU",
    dial_code: "+262",
    flag: "https://flagcdn.com/re.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Romania",
    code: "RO",
    country_code: "ROU",
    dial_code: "+40",
    flag: "https://flagcdn.com/ro.svg",
    currency: "RON",
    currency_name: "Romanian leu",
    currency_symbol: "lei",
  },
  {
    name: "Russia",
    code: "RU",
    country_code: "RUS",
    dial_code: "+73",
    flag: "https://flagcdn.com/ru.svg",
    currency: "RUB",
    currency_name: "Russian ruble",
    currency_symbol: "₽",
  },
  {
    name: "Rwanda",
    code: "RW",
    country_code: "RWA",
    dial_code: "+250",
    flag: "https://flagcdn.com/rw.svg",
    currency: "RWF",
    currency_name: "Rwandan franc",
    currency_symbol: "Fr",
  },
  {
    name: "Saint Barthélemy",
    code: "BL",
    country_code: "BLM",
    dial_code: "+590",
    flag: "https://flagcdn.com/bl.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
    country_code: "SHN",
    dial_code: "+290",
    flag: "https://flagcdn.com/sh.svg",
    currency: "GBP",
    currency_name: "Pound sterling",
    currency_symbol: "£",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    country_code: "KNA",
    dial_code: "+1869",
    flag: "https://flagcdn.com/kn.svg",
    currency: "XCD",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    country_code: "LCA",
    dial_code: "+1758",
    flag: "https://flagcdn.com/lc.svg",
    currency: "XCD",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Saint Martin",
    code: "MF",
    country_code: "MAF",
    dial_code: "+590",
    flag: "https://flagcdn.com/mf.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Saint Pierre and Miquelon",
    code: "PM",
    country_code: "SPM",
    dial_code: "+508",
    flag: "https://flagcdn.com/pm.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    country_code: "VCT",
    dial_code: "+1784",
    flag: "https://flagcdn.com/vc.svg",
    currency: "XCD",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Samoa",
    code: "WS",
    country_code: "WSM",
    dial_code: "+685",
    flag: "https://flagcdn.com/ws.svg",
    currency: "WST",
    currency_name: "Samoan tālā",
    currency_symbol: "T",
  },
  {
    name: "San Marino",
    code: "SM",
    country_code: "SMR",
    dial_code: "+378",
    flag: "https://flagcdn.com/sm.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "São Tomé and Príncipe",
    code: "ST",
    country_code: "STP",
    dial_code: "+239",
    flag: "https://flagcdn.com/st.svg",
    currency: "STN",
    currency_name: "São Tomé and Príncipe dobra",
    currency_symbol: "Db",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    country_code: "SAU",
    dial_code: "+966",
    flag: "https://flagcdn.com/sa.svg",
    currency: "SAR",
    currency_name: "Saudi riyal",
    currency_symbol: "ر.س",
  },
  {
    name: "Senegal",
    code: "SN",
    country_code: "SEN",
    dial_code: "+221",
    flag: "https://flagcdn.com/sn.svg",
    currency: "XOF",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Serbia",
    code: "RS",
    country_code: "SRB",
    dial_code: "+381",
    flag: "https://flagcdn.com/rs.svg",
    currency: "RSD",
    currency_name: "Serbian dinar",
    currency_symbol: "дин.",
  },
  {
    name: "Seychelles",
    code: "SC",
    country_code: "SYC",
    dial_code: "+248",
    flag: "https://flagcdn.com/sc.svg",
    currency: "SCR",
    currency_name: "Seychellois rupee",
    currency_symbol: "₨",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    country_code: "SLE",
    dial_code: "+232",
    flag: "https://flagcdn.com/sl.svg",
    currency: "SLL",
    currency_name: "Sierra Leonean leone",
    currency_symbol: "Le",
  },
  {
    name: "Singapore",
    code: "SG",
    country_code: "SGP",
    dial_code: "+65",
    flag: "https://flagcdn.com/sg.svg",
    currency: "SGD",
    currency_name: "Singapore dollar",
    currency_symbol: "$",
  },
  {
    name: "Sint Maarten",
    code: "SX",
    country_code: "SXM",
    dial_code: "+1721",
    flag: "https://flagcdn.com/sx.svg",
    currency: "ANG",
    currency_name: "Netherlands Antillean guilder",
    currency_symbol: "ƒ",
  },
  {
    name: "Slovakia",
    code: "SK",
    country_code: "SVK",
    dial_code: "+421",
    flag: "https://flagcdn.com/sk.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Slovenia",
    code: "SI",
    country_code: "SVN",
    dial_code: "+386",
    flag: "https://flagcdn.com/si.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    country_code: "SLB",
    dial_code: "+677",
    flag: "https://flagcdn.com/sb.svg",
    currency: "SBD",
    currency_name: "Solomon Islands dollar",
    currency_symbol: "$",
  },
  {
    name: "Somalia",
    code: "SO",
    country_code: "SOM",
    dial_code: "+252",
    flag: "https://flagcdn.com/so.svg",
    currency: "SOS",
    currency_name: "Somali shilling",
    currency_symbol: "Sh",
  },
  {
    name: "South Africa",
    code: "ZA",
    country_code: "ZAF",
    dial_code: "+27",
    flag: "https://flagcdn.com/za.svg",
    currency: "ZAR",
    currency_name: "South African rand",
    currency_symbol: "R",
  },
  {
    name: "South Georgia",
    code: "GS",
    country_code: "SGS",
    dial_code: "+500",
    flag: "https://flagcdn.com/gs.svg",
    currency: "SHP",
    currency_name: "Saint Helena pound",
    currency_symbol: "£",
  },
  {
    name: "South Korea",
    code: "KR",
    country_code: "KOR",
    dial_code: "+82",
    flag: "https://flagcdn.com/kr.svg",
    currency: "KRW",
    currency_name: "South Korean won",
    currency_symbol: "₩",
  },
  {
    name: "South Sudan",
    code: "SS",
    country_code: "SSD",
    dial_code: "+211",
    flag: "https://flagcdn.com/ss.svg",
    currency: "SSP",
    currency_name: "South Sudanese pound",
    currency_symbol: "£",
  },
  {
    name: "Spain",
    code: "ES",
    country_code: "ESP",
    dial_code: "+34",
    flag: "https://flagcdn.com/es.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    country_code: "LKA",
    dial_code: "+94",
    flag: "https://flagcdn.com/lk.svg",
    currency: "LKR",
    currency_name: "Sri Lankan rupee",
    currency_symbol: "Rs  රු",
  },
  {
    name: "Sudan",
    code: "SD",
    country_code: "SDN",
    dial_code: "+249",
    flag: "https://flagcdn.com/sd.svg",
    currency: "SDG",
    currency_name: "Sudanese pound",
    currency_symbol: "ج.س",
  },
  {
    name: "Suriname",
    code: "SR",
    country_code: "SUR",
    dial_code: "+597",
    flag: "https://flagcdn.com/sr.svg",
    currency: "SRD",
    currency_name: "Surinamese dollar",
    currency_symbol: "$",
  },
  {
    name: "Svalbard and Jan Mayen",
    code: "SJ",
    country_code: "SJM",
    dial_code: "+4779",
    flag: "https://flagcdn.com/sj.svg",
    currency: "NOK",
    currency_name: "krone",
    currency_symbol: "kr",
  },
  {
    name: "Sweden",
    code: "SE",
    country_code: "SWE",
    dial_code: "+46",
    flag: "https://flagcdn.com/se.svg",
    currency: "SEK",
    currency_name: "Swedish krona",
    currency_symbol: "kr",
  },
  {
    name: "Switzerland",
    code: "CH",
    country_code: "CHE",
    dial_code: "+41",
    flag: "https://flagcdn.com/ch.svg",
    currency: "CHF",
    currency_name: "Swiss franc",
    currency_symbol: "Fr.",
  },
  {
    name: "Syria",
    code: "SY",
    country_code: "SYR",
    dial_code: "+963",
    flag: "https://flagcdn.com/sy.svg",
    currency: "SYP",
    currency_name: "Syrian pound",
    currency_symbol: "£",
  },
  {
    name: "Taiwan",
    code: "TW",
    country_code: "TWN",
    dial_code: "+886",
    flag: "https://flagcdn.com/tw.svg",
    currency: "TWD",
    currency_name: "New Taiwan dollar",
    currency_symbol: "$",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    country_code: "TJK",
    dial_code: "+992",
    flag: "https://flagcdn.com/tj.svg",
    currency: "TJS",
    currency_name: "Tajikistani somoni",
    currency_symbol: "ЅМ",
  },
  {
    name: "Tanzania",
    code: "TZ",
    country_code: "TZA",
    dial_code: "+255",
    flag: "https://flagcdn.com/tz.svg",
    currency: "TZS",
    currency_name: "Tanzanian shilling",
    currency_symbol: "Sh",
  },
  {
    name: "Thailand",
    code: "TH",
    country_code: "THA",
    dial_code: "+66",
    flag: "https://flagcdn.com/th.svg",
    currency: "THB",
    currency_name: "Thai baht",
    currency_symbol: "฿",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    country_code: "TLS",
    dial_code: "+670",
    flag: "https://flagcdn.com/tl.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Togo",
    code: "TG",
    country_code: "TGO",
    dial_code: "+228",
    flag: "https://flagcdn.com/tg.svg",
    currency: "XOF",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Tokelau",
    code: "TK",
    country_code: "TKL",
    dial_code: "+690",
    flag: "https://flagcdn.com/tk.svg",
    currency: "NZD",
    currency_name: "New Zealand dollar",
    currency_symbol: "$",
  },
  {
    name: "Tonga",
    code: "TO",
    country_code: "TON",
    dial_code: "+676",
    flag: "https://flagcdn.com/to.svg",
    currency: "TOP",
    currency_name: "Tongan paʻanga",
    currency_symbol: "T$",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    country_code: "TTO",
    dial_code: "+1868",
    flag: "https://flagcdn.com/tt.svg",
    currency: "TTD",
    currency_name: "Trinidad and Tobago dollar",
    currency_symbol: "$",
  },
  {
    name: "Tunisia",
    code: "TN",
    country_code: "TUN",
    dial_code: "+216",
    flag: "https://flagcdn.com/tn.svg",
    currency: "TND",
    currency_name: "Tunisian dinar",
    currency_symbol: "د.ت",
  },
  {
    name: "Turkey",
    code: "TR",
    country_code: "TUR",
    dial_code: "+90",
    flag: "https://flagcdn.com/tr.svg",
    currency: "TRY",
    currency_name: "Turkish lira",
    currency_symbol: "₺",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    country_code: "TKM",
    dial_code: "+993",
    flag: "https://flagcdn.com/tm.svg",
    currency: "TMT",
    currency_name: "Turkmenistan manat",
    currency_symbol: "m",
  },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    country_code: "TCA",
    dial_code: "+1649",
    flag: "https://flagcdn.com/tc.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Tuvalu",
    code: "TV",
    country_code: "TUV",
    dial_code: "+688",
    flag: "https://flagcdn.com/tv.svg",
    currency: "AUD",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "Uganda",
    code: "UG",
    country_code: "UGA",
    dial_code: "+256",
    flag: "https://flagcdn.com/ug.svg",
    currency: "UGX",
    currency_name: "Ugandan shilling",
    currency_symbol: "Sh",
  },
  {
    name: "Ukraine",
    code: "UA",
    country_code: "UKR",
    dial_code: "+380",
    flag: "https://flagcdn.com/ua.svg",
    currency: "UAH",
    currency_name: "Ukrainian hryvnia",
    currency_symbol: "₴",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    country_code: "UAE",
    dial_code: "+971",
    flag: "https://flagcdn.com/ae.svg",
    currency: "AED",
    currency_name: "United Arab Emirates dirham",
    currency_symbol: "د.إ",
  },
  {
    name: "United Kingdom",
    code: "GB",
    country_code: "GBR",
    dial_code: "+44",
    flag: "https://flagcdn.com/gb.svg",
    currency: "GBP",
    currency_name: "British pound",
    currency_symbol: "£",
  },
  {
    name: "United States",
    code: "US",
    country_code: "USA",
    dial_code: "+1201",
    flag: "https://flagcdn.com/us.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    country_code: "UMI",
    dial_code: "+268",
    flag: "https://flagcdn.com/um.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "United States Virgin Islands",
    code: "VI",
    country_code: "VIR",
    dial_code: "+1340",
    flag: "https://flagcdn.com/vi.svg",
    currency: "USD",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Uruguay",
    code: "UY",
    country_code: "URY",
    dial_code: "+598",
    flag: "https://flagcdn.com/uy.svg",
    currency: "UYU",
    currency_name: "Uruguayan peso",
    currency_symbol: "$",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    country_code: "UZB",
    dial_code: "+998",
    flag: "https://flagcdn.com/uz.svg",
    currency: "UZS",
    currency_name: "Uzbekistani soʻm",
    currency_symbol: "so'm",
  },
  {
    name: "Vanuatu",
    code: "VU",
    country_code: "VUT",
    dial_code: "+678",
    flag: "https://flagcdn.com/vu.svg",
    currency: "VUV",
    currency_name: "Vanuatu vatu",
    currency_symbol: "Vt",
  },
  {
    name: "Vatican City",
    code: "VA",
    country_code: "VAT",
    dial_code: "+3906698",
    flag: "https://flagcdn.com/va.svg",
    currency: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Venezuela",
    code: "VE",
    country_code: "VEN",
    dial_code: "+58",
    flag: "https://flagcdn.com/ve.svg",
    currency: "VES",
    currency_name: "Venezuelan bolívar soberano",
    currency_symbol: "Bs.S.",
  },
  {
    name: "Vietnam",
    code: "VN",
    country_code: "VNM",
    dial_code: "+84",
    flag: "https://flagcdn.com/vn.svg",
    currency: "VND",
    currency_name: "Vietnamese đồng",
    currency_symbol: "₫",
  },
  {
    name: "Wallis and Futuna",
    code: "WF",
    country_code: "WLF",
    dial_code: "+681",
    flag: "https://flagcdn.com/wf.svg",
    currency: "XPF",
    currency_name: "CFP franc",
    currency_symbol: "₣",
  },
  {
    name: "Western Sahara",
    code: "EH",
    country_code: "ESH",
    dial_code: "+2125288",
    flag: "https://flagcdn.com/eh.svg",
    currency: "DZD",
    currency_name: "Algerian dinar",
    currency_symbol: "دج",
  },
  {
    name: "Yemen",
    code: "YE",
    country_code: "YEM",
    dial_code: "+967",
    flag: "https://flagcdn.com/ye.svg",
    currency: "YER",
    currency_name: "Yemeni rial",
    currency_symbol: "﷼",
  },
  {
    name: "Zambia",
    code: "ZM",
    country_code: "ZMB",
    dial_code: "+260",
    flag: "https://flagcdn.com/zm.svg",
    currency: "ZMW",
    currency_name: "Zambian kwacha",
    currency_symbol: "ZK",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    country_code: "ZWE",
    dial_code: "+263",
    flag: "https://flagcdn.com/zw.svg",
    currency: "ZWL",
    currency_name: "Zimbabwean dollar",
    currency_symbol: "$",
  },
];

export const fetchCountriesData = async (): Promise<ICountry[]> => {
  type CurrencyInfo = {
    name: string;
    symbol: string;
  };

  try {
    const response = await fetch("https://restcountries.com/v3.1/all");
    const countries: any[] = await response.json();

    const formattedCountries: ICountry[] = countries
      .map((country) => {
        const currencyCode: string = country.currencies
          ? Object.keys(country.currencies)[0]
          : "N/A";
        const currencyInfo: CurrencyInfo = country.currencies
          ? country.currencies[currencyCode]
          : { name: "N/A", symbol: "N/A" };

        return {
          name: country.name?.common || "N/A",
          code: country.cca2 || "N/A",
          country_code: country.cca3 || "N/A",
          dial_code:
            country.idd?.root && country.idd?.suffixes
              ? `${country.idd.root}${country.idd.suffixes[0]}`
              : "N/A",
          flag: `https://flagcdn.com/${country.cca2?.toLowerCase()}.svg`,
          currency: currencyCode || "N/A",
          currency_name: currencyInfo?.name || "N/A",
          currency_symbol: currencyInfo?.symbol || "N/A",
        };
      })
      .sort((a, b) => a.name.localeCompare(b.name));

    console.log(formattedCountries);
    return formattedCountries;
  } catch (error) {
    console.error("Error fetching countries data:", error);
    return [];
  }
};
